### PR TITLE
Splitting assignments, and fixing various commenting bugs.  Fixes #17

### LINKED ISSUE #17: Add button to dissolve a team submission and resubmit copies of it for all students
ccis:  blerner commented on Mar 3

Sometimes a submission happens "by a team" but one team member deserves all the credit. Right now it's painful to handle that grading scenario. We should have a button to dissolve the team, create the necessary number of singleton teams, copy the submission and resubmit it on behalf of each student. All grader outputs should be copied over, too.

### PR DESCRIPTION
**Pull request by blerner**

### CODE REVIEW

**Comment by blerner** [comment]
@NatTuck the failing test here has nothing to do with my code -- it's something to do with mailer configuration stuff, and I've been seeing sporadic failures on it when I run tests locally.  Depending on the test seed (and therefore the order of tests being run), it passes or fails... dunno what's going on.

File: app/controllers/submissions_controller.rb [hunk 1]
```diff
@@ -169,19 +147,60 @@ def update_plagiarism
...
+    @submission.users.each do |student|
+      split_sub(@submission, student)
+    end
+    redirect_to course_assignment_path(@course, @assignment),
+                notice: "Group submission split for #{@submission.users.map(&:name).join(', ')}"
+  end
+
+  def split_sub(orig_sub, for_user, score = nil)
+    team = orig_sub.team
+    if team
```
Comment (NatTuck) [inline app/controllers/submissions_controller.rb]: Does this make sense if there isn't a team?

Comment (NatTuck) [inline app/controllers/submissions_controller.rb]: Should this batch of changes be in a transaction, with save! used to kill the transaction if anything fails?

File: app/controllers/submissions_controller.rb [hunk 2]
```diff
@@ -169,19 +147,60 @@ def update_plagiarism
...
+      # Construct a one-use team, so that this student can be graded in isolation
+      team = Team.new(
+        course: @course,
+        start_date: orig_sub.created_at,
+        end_date: orig_sub.created_at)
+      team.users = [for_user]
+      team.save
+    end
+    # Create the new submission, reusing the prior submitted file
+    sub = Submission.new(
```
Comment (NatTuck) [inline app/controllers/submissions_controller.rb]: To copy model objects it's probably clearer to use .dup and then change the differences.

File: app/controllers/submissions_controller.rb [hunk 3]
```diff
@@ -169,19 +147,60 @@ def update_plagiarism
...
+      ignore_late_penalty: false,
+      score: score || orig_sub.score,
+      team: team,
+      upload_id: @submission.upload_id,
+      type: @submission.type)
+    sub.save
+    sub.set_used_sub!
+    # Copy any grades
+    orig_sub.grades.each do |g|
+      new_g = Grade.new(
```
Comment (NatTuck) [inline app/controllers/submissions_controller.rb]: .dup ?

**Comment by NatTuck** [comment]
I think #42 has the testing thing fixed by adding

`config.action_mailer.default_url_options = { host: 'localhost:3001' } `

to the end of config/environments/test.rb

File: app/controllers/submissions_controller.rb (hunk 1 above)
Comment (blerner) [inline app/controllers/submissions_controller.rb]: If there's no team, it still produces a self-consistent copy of the submission.  This helper can be called from update_plagiarism, too, which might be invoked on a submission with only a single student.

I don't see how anything could fail in this code sequence, but yes, it probably should be in a transaction.  I don't know how to write those in rails, though; I've not been able to figure it out from the documentation.  (I don't understand which class is the "right" one to invoke .transaction on, how nested transactions could be coded in practice, how to recover from them gracefully, or basically anything else about how to use that API idiomatically.)

File: app/controllers/submissions_controller.rb (hunk 2 above)
Comment (blerner) [inline app/controllers/submissions_controller.rb]: I thought about that, but since most of the fields are different, and since .dup doesn't preserve created_at (which is one of the fields I want to preserve), it seemed clearer to me to be explicit about the full property set for these objects.

File: app/controllers/submissions_controller.rb (hunk 3 above)
Comment (blerner) [inline app/controllers/submissions_controller.rb]: Maybe, yeah.  Here I kept it as is, in consistency with the explicit creation code above, but since only one attribute changes here, it is shorter to use .dup
